## NumPy Library
NumPy is the fundamental package for scientific computing with Python. It contains:
    Powerful N dimensional array object
    Sophisticated broadcasting funcitons
    tools for integrating C/C++ and Frotran code
    useful for linear algebra, Fourier transform, and random number capabilites
    

In [1]:
import sys
import numpy as np

## Basic Array's with NumPy

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1,2,3,4])

In [4]:
b = np.array([0, .5, 1, 1.5, 2])

In [5]:
a[0], a[1]

(1, 2)

In [6]:
a[0:]

array([1, 2, 3, 4])

In [7]:
a[1:3]

array([2, 3])

In [8]:
a[1:-1]

array([2, 3])

In [9]:
a[::2]

array([1, 3])

In [10]:
b[0],b[2],b[-1]

(0.0, 1.0, 2.0)

In [11]:
b[[0, 2, -1]]# multi indexing

array([0., 1., 2.])

## Array Types

In [12]:
a

array([1, 2, 3, 4])

In [13]:
a.dtype

dtype('int32')

In [14]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [15]:
b.dtype

dtype('float64')

In [16]:
np.array([1, 2, 3, 4], dtype=np.float) # makes the array float type

array([1., 2., 3., 4.])

In [17]:
c = np.array(['a','b','c']) #storing strings

In [18]:
c.dtype

dtype('<U1')

## Dimensions and shapes

In [19]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

In [20]:
A.shape

(2, 3)

In [21]:
A.ndim # Number of Dimensions ie 2-d

2

In [22]:
A.size # total size

6

In [23]:
B = np.array([
    [
    [12,11,10],
    [9,8,7]
    ],
    [
    [6,5,4],
    [3,2,1]
    ]
]) # 3 dimensional array

In [24]:
B.shape

(2, 2, 3)

In [25]:
B.ndim # Number of dimensions ie 3-D

3

In [26]:
B.size

12

In [27]:
# Square matrix
A = np.array([
#.   0 1 2    
    [1,2,3],# 0 
    [4,5,6],# 1
    [7,8,9] # 2
])

In [28]:
A[1]

array([4, 5, 6])

In [29]:
A[1] # Gives Row of 1

array([4, 5, 6])

In [30]:
A[1][0] # A[d1,d2,d3,d4]

4

In [31]:
A[0:2] #first two of d1 thus first 2 rows

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
A[:, :2] # first two of d2 thus first 2 colomns

array([[1, 2],
       [4, 5],
       [7, 8]])

In [33]:
A[:2,:2] # fisrt two of d1, first two of d2

array([[1, 2],
       [4, 5]])

In [34]:
A[1] = np.array([10,10,10]) # change Row 1 to new array

In [35]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

## Summary statistics

In [36]:
a = np.array([1, 2, 3, 4])

In [37]:
a.sum()

10

In [38]:
a.mean()

2.5

In [39]:
a.std()

1.118033988749895

In [40]:
a.var()

1.25

In [41]:
A = np.array([
#.   0 1 2    
    [1,2,3],# 0 
    [4,5,6],# 1
    [7,8,9] # 2
])

In [42]:
A.sum()
A.mean()
A.std()

2.581988897471611

In [43]:
A.sum(axis=0) # Sum of each coloumb

array([12, 15, 18])

In [44]:
A.sum(axis=1) # Sum of each row

array([ 6, 15, 24])

In [45]:
A.mean(axis=0)

array([4., 5., 6.])

In [46]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

## Broadcasting and Vecotrized operations

In [47]:
a = np.arange(4)

In [48]:
a

array([0, 1, 2, 3])

In [49]:
a + 10 # Adds 10 to each element

array([10, 11, 12, 13])

In [50]:
a * 10

array([ 0, 10, 20, 30])

In [51]:
a

array([0, 1, 2, 3])

In [52]:
a += 100 # Makes it so it stores new values in a

In [53]:
a

array([100, 101, 102, 103])

In [54]:
l = [0, 1, 2, 3]

In [55]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [56]:
a = np.arange(4)

In [57]:
b = np.array([10,10,10,10])

In [58]:
a + b # addes elements of arrays of the same shape 

array([10, 11, 12, 13])

## Boolean arrays (aka masks)

In [59]:
a = np.arange(4)

In [60]:
a

array([0, 1, 2, 3])

In [61]:
a[[0,-1]] # first and last element

array([0, 3])

In [62]:
a[[True,False,False,True]] #using boolean

array([0, 3])

In [63]:
a >= 2 # Checks each element in a and returns boolean

array([False, False,  True,  True])

In [64]:
a[a >= 2] #output actual element that meets condiction a >= 2

array([2, 3])

In [65]:
a.mean()

1.5

In [66]:
a[a > a.mean()] # outputs element that is greater than a.mean()

array([2, 3])

In [67]:
a[~(a > a.mean())] # outputs elements that reutrn FALSE to condition greater than a.mean()

array([0, 1])

In [68]:
a[(a == 0) | (a ==1)] # OR in boolean is |

array([0, 1])

In [69]:
a[(a <= 2) & (a%2 == 0)] # AND in boolean is &

array([0, 2])

In [70]:
A = np.random.randint(100, size=(3,3))

In [71]:
A

array([[98, 29, 79],
       [97, 76, 41],
       [18, 89,  2]])

In [72]:
A[np.array([
    [True,False,True],
    [False, True,False],
    [True, False, True]
])]

array([98, 79, 76, 18,  2])

In [73]:
A > 30

array([[ True, False,  True],
       [ True,  True,  True],
       [False,  True, False]])

## Linear Algebra

In [74]:
A = np.array([   
    [1,2,3],
    [4,5,6],
    [7,8,9] 
])

In [78]:
B = np.array([
    [6,5],
    [4,3],
    [2,1] 
])

In [79]:
A.dot(B) # Dot product A.B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [80]:
A @ B # Cross product A x B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [81]:
B.T # Transpose B

array([[6, 4, 2],
       [5, 3, 1]])

In [82]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

## Size of objects in Memory

In [83]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [84]:
#Longs are even larger
sys.getsizeof(10**100)

72

In [85]:
# NumPy size is much smaller
np.dtype(int).itemsize

4

In [86]:
np.dtype(float).itemsize

8

## Lists are even larger

In [87]:
# one element list
sys.getsizeof([1])

64

In [88]:
np.array([1]).nbytes

4

## Performance is also important

In [89]:
l = list(range(1000))

In [90]:
a = np.arange(1000)

In [91]:
%time np.sum(a**2) # square all elements in the list

Wall time: 0 ns


332833500

In [92]:
%time sum([x ** 2 for x in l])

Wall time: 999 µs


332833500

## Useful NumPy functions

### random

In [93]:
np.random.random(size=3)

array([0.59175077, 0.99518494, 0.10624484])

In [94]:
np.random.normal(size=3)

array([ 0.76292427, -1.38166155, -1.20378214])

In [95]:
np.random.rand(2,4)

array([[0.03038904, 0.24967053, 0.08591527, 0.55061196],
       [0.07623455, 0.03767954, 0.59707797, 0.72292886]])

In [96]:
### arange
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [98]:
np.arange(0,1,.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [99]:
### reshape

In [101]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [102]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

### linspace

In [104]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [106]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [107]:
np.linspace(0,1,20,False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

### Zeors, ones, empty

In [108]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [112]:
np.zeros((3,3), dtype=np.int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.ones